package com.awrdev.cameracomposetest.common

val UNIT_LENGTH = 250
val ERROR_RATE = UNIT_LENGTH / 2
val DOT_LENGTH = IntRange(UNIT_LENGTH - ERROR_RATE, UNIT_LENGTH + ERROR_RATE)
val DASH_LENGTH = IntRange(3*UNIT_LENGTH - ERROR_RATE, 3*UNIT_LENGTH + ERROR_RATE)
val LETTER_BRAKE_LENGTH = IntRange((1.5*UNIT_LENGTH).toInt(), 4*UNIT_LENGTH)
val SPACE_LENGTH = IntRange(7*UNIT_LENGTH - ERROR_RATE, 8*UNIT_LENGTH + ERROR_RATE)